version: '2.1'

services:
  admin:
    network_mode: "host"
    restart: "always"
    build: .
    image: admin-server
    volumes:
      - /security:/security
    environment:
      TZ: "Europe/Amsterdam"    
    healthcheck:
      test: "curl -sS http://localhost:2222/health"
      interval: 1s
      timeout: 60s
      retries: 120
    container_name: gundmann-admin